checkstyle.xml, pom.xml, src/main/java/com/selfxdsd/storage/MySql.java, src/main/java/com/selfxdsd/storage/SelfJooq.java, src/main/java/com/selfxdsd/storage/SelfUsers.java, src/main/java/com/selfxdsd/storage/generated/jooq/tables/SlfUsersXdsd.java, src/main/java/com/selfxdsd/storage/generated/jooq/tables/records/SlfUsersXdsdRecord.java, src/test/java/com/selfxdsd/storage/H2Database.java, src/test/java/com/selfxdsd/storage/SelfJooqTestCase.java, src/test/java/com/selfxdsd/storage/SelfUsersITCase.java, src/test/java/com/selfxdsd/storage/package-info.java, src/test/resources/createDb.sql, src/test/resources/insertTestData.sql
Fixes #8 
Integration testing setup with H2 on-disk DB (via ``sql-maven-plugin``) and ``maven-failsafe-plugin``, all under the Maven profile called ``itcases``.
=> Integration Testing set up

pom.xml
=> #10 self-core github packages

src/main/java/com/selfxdsd/storage/SelfUsers.java, src/test/java/com/selfxdsd/storage/SelfUsersITCase.java, src/test/resources/insertTestData.sql
=> #13 SelfUsers.iterator implemented and tested

src/main/java/com/selfxdsd/storage/SelfProjects.java, src/test/java/com/selfxdsd/storage/SelfJooqTestCase.java, src/test/java/com/selfxdsd/storage/SelfProjectsITCase.java, src/test/resources/insertTestData.sql
fixes #15 
* Implemented SelfProjects.getById
* added INSERT statements for test data
* added integration test
* left puzzle to continue work.
=> #15 SelfProjects.getById implemented and tested

src/main/java/com/selfxdsd/storage/SelfUsers.java, src/test/java/com/selfxdsd/storage/SelfUsersITCase.java
PR for #12 
Added puzzle to update `signUp` when access token is available to User.
=> #12 Implemented and tested `SelfUsers#signUp`.

src/main/java/com/selfxdsd/storage/SelfPms.java, src/test/java/com/selfxdsd/storage/SelfPmsITCase.java
fixes #19 
* Implemented ``SelfPms.getById(...)``
* left puzzle to continue work
* tests.
=> #19 SelfPms.getById + puzzle; needs unit tests

src/main/java/com/selfxdsd/storage/SelfPms.java, src/test/java/com/selfxdsd/storage/SelfPmsITCase.java
=> #23 - Finished implementing and testing SelfPms.

src/main/java/com/selfxdsd/storage/SelfContributors.java, src/main/java/com/selfxdsd/storage/SelfJooq.java, src/test/java/com/selfxdsd/storage/SelfContributorsITCase.java, src/test/java/com/selfxdsd/storage/SelfJooqTestCase.java, src/test/resources/insertTestData.sql
Fixes #30 
Implemented SelfContributors
Wrote integration tests.
=> #30 SelfContributors implemented and tested

src/main/java/com/selfxdsd/storage/PagedIterator.java, src/main/java/com/selfxdsd/storage/SelfPms.java, src/test/java/com/selfxdsd/storage/PagedIteratorTestCase.java
PR for #29 
Fixed bug in next().
Added constructor method.
Removed puzzle.
=> #29 Refactored and tested PagedIterator

src/main/java/com/selfxdsd/storage/PagedIterator.java, src/main/java/com/selfxdsd/storage/SelfContracts.java, src/test/java/com/selfxdsd/storage/SelfContractsITCase.java, src/test/resources/insertTestData.sql
Fixes #32 
Implemented the iterator, added test for it and left puzzle to continue work.
=> #32 SelfContracts.iterator, integration test + puzzle

src/main/java/com/selfxdsd/storage/SelfProjects.java, src/test/java/com/selfxdsd/storage/SelfProjectsITCase.java, src/test/resources/insertTestData.sql
Fixes #18 
Implemented and tested all remaining methods of ``SelfProjects``.
=> Finished implementing SelfProjects

src/main/java/com/selfxdsd/storage/SelfTasks.java, src/test/java/com/selfxdsd/storage/SelfJooqTestCase.java
Fixes #37 
Started implementing the class.
Left puzzle to continue work.
=> Started implementing SelfTasks

pom.xml, src/main/java/com/selfxdsd/storage/SelfContracts.java, src/main/java/com/selfxdsd/storage/SelfJooq.java, src/main/java/com/selfxdsd/storage/SelfTasks.java, src/test/java/com/selfxdsd/storage/SelfTasksITCase.java, src/test/resources/insertTestData.sql
Fixes #39 
* implemented getById
* wrote tests for it
* left puzzle to continue work
=> SelfTasks.getById implemented

.gitignore, .rultor.yml, README.md, pom.xml, release.sh
fixes #43 
* Rultor release config
* Maven plugin for javadocs and sources
=> #43 Release setup

src/main/java/com/selfxdsd/storage/SelfTasks.java, src/test/java/com/selfxdsd/storage/SelfTasksITCase.java, src/test/resources/insertTestData.sql
PR for #41 
* Implemented and tested ``SelfTasks.ofContributor``;
* Implemented and tested ``SelfTasks.ofProject``;
* Left puzzle to continue work;
=> #41 SelfTasks.ofContributor/ofProject

src/main/java/com/selfxdsd/storage/MySql.java, src/main/java/com/selfxdsd/storage/SelfContracts.java, src/main/java/com/selfxdsd/storage/SelfContributors.java, src/main/java/com/selfxdsd/storage/SelfJooq.java, src/main/java/com/selfxdsd/storage/SelfPms.java, src/main/java/com/selfxdsd/storage/SelfProjects.java, src/main/java/com/selfxdsd/storage/SelfTasks.java, src/main/java/com/selfxdsd/storage/SelfUsers.java, src/test/java/com/selfxdsd/storage/H2Database.java
fixes #49 
There is now only one DB Connection per Storage. 
Storage will become Autoclosable and be closed by the framework when the User Session or Request ends.
=> #49 DB.connect/close at Storage level

src/main/java/com/selfxdsd/storage/SelfTasks.java, src/test/java/com/selfxdsd/storage/SelfTasksITCase.java
PR for #53 
* Implemented and tested SelfTasks.iterator
* Implemented and tested SelfTasks.unassigned
=> Finished implementing SelfTasks

src/main/java/com/selfxdsd/storage/SelfContracts.java, src/test/java/com/selfxdsd/storage/SelfContractsITCase.java, src/test/java/com/selfxdsd/storage/SelfJooqTestCase.java
PR for #35 
Implemented and tested ``SelfContracts.findById``.
Left puzzle to continue work.
=> #35 SelfContracts.findById

src/main/java/com/selfxdsd/storage/SelfContracts.java, src/test/java/com/selfxdsd/storage/SelfContractsITCase.java, src/test/resources/insertTestData.sql
=> #57 Finished implementing and testing SelfContracts.

pom.xml, src/main/java/com/selfxdsd/storage/SelfContributors.java, src/main/java/com/selfxdsd/storage/SelfTasks.java, src/test/java/com/selfxdsd/storage/SelfContributorsITCase.java
=> #60 updated self-core to 0.0.6

src/main/java/com/selfxdsd/storage/SelfTasks.java, src/test/java/com/selfxdsd/storage/SelfTasksITCase.java, src/test/resources/insertTestData.sql
Fixes #62 
Implemented and wrote tests for SelfTasks.ofContract
Added test data.
=> #62 SelfTasks.ofContract implemented and tested

pom.xml, src/main/java/com/selfxdsd/storage/SelfContributors.java, src/main/java/com/selfxdsd/storage/SelfJooq.java, src/main/java/com/selfxdsd/storage/SelfTasks.java, src/test/java/com/selfxdsd/storage/SelfContributorsITCase.java
PR for #66 
Left puzzles to continue work.
=> #55 self-core 0.0.8

src/main/java/com/selfxdsd/storage/SelfInvoices.java, src/main/java/com/selfxdsd/storage/SelfJooq.java, src/main/java/com/selfxdsd/storage/SelfPms.java, src/test/java/com/selfxdsd/storage/SelfInvoicesITCase.java, src/test/java/com/selfxdsd/storage/SelfJooqTestCase.java, src/test/resources/insertTestData.sql
PR for #69 
SelfInvoices implemented and tested
Left puzzle for InvoicedTasks and then SelfInvoices.ofContract.
=> #69 SelfInvoices implemented and tested

src/main/java/com/selfxdsd/storage/SelfInvoicedTasks.java, src/main/java/com/selfxdsd/storage/SelfInvoices.java, src/main/java/com/selfxdsd/storage/SelfTasks.java, src/test/java/com/selfxdsd/storage/SelfInvoicedTasksITCase.java
PR for #75 
Implemented and tested ofInvoice(...) method
Left some puzzles.
=> #75 SelfInvoicedTasks.ofInvoice

src/main/java/com/selfxdsd/storage/Database.java, src/main/java/com/selfxdsd/storage/SelfProjects.java, src/test/java/com/selfxdsd/storage/SelfContributorsITCase.java, src/test/java/com/selfxdsd/storage/SelfUsersITCase.java
Fixes #81 
* ``Database`` should not be closed arbitrarily within the storage
* Made ``Database`` implement ``Closeable`` instead of ``AutoCloseable``.
=> #81 Fix DB Closing issues

pom.xml, src/main/java/com/selfxdsd/storage/SelfInvoices.java, src/main/java/com/selfxdsd/storage/SelfTasks.java, src/main/java/com/selfxdsd/storage/SelfUsers.java, src/test/java/com/selfxdsd/storage/SelfInvoicesITCase.java, src/test/java/com/selfxdsd/storage/SelfUsersITCase.java
Fixes #84 
* Updated to self-core 0.0.10
* Fixed param order of SelfUsers.signUp
=> #84 fixed parameter order

pom.xml
=> #85 core is provided

src/main/java/com/selfxdsd/storage/SelfInvoices.java, src/test/java/com/selfxdsd/storage/SelfInvoicesITCase.java
=> #78 SelfInvoices#ofContract implemented & tested.

pom.xml, src/main/java/com/selfxdsd/storage/SelfInvoicedTasks.java, src/test/java/com/selfxdsd/storage/SelfInvoicedTasksITCase.java
=> #89 updated core to 0.0.11

src/main/java/com/selfxdsd/storage/SelfInvoicedTasks.java, src/test/java/com/selfxdsd/storage/SelfInvoicedTasksITCase.java
PR for #79 
Contract is read from the Invoice instead of n times from the DB. 
Left puzzle to fix a test.
=> #79 get Contract from Invoice

src/main/java/com/selfxdsd/storage/SelfProjects.java
=> #94 use repo.owner() when returning registered Project

pom.xml, src/main/java/com/selfxdsd/storage/PagedIterator.java, src/main/java/com/selfxdsd/storage/SelfContributors.java, src/main/java/com/selfxdsd/storage/SelfInvoices.java, src/main/java/com/selfxdsd/storage/SelfProjects.java, src/test/java/com/selfxdsd/storage/SelfProjectsITCase.java
- Some fixes.
- SelfProjects tested and removed PagedIterator from iteration.
- PagedIterator deprecated.
Fixes for #98
=> #98 SelfProjects fixes+paging tests and PagedIterator deprecated.

src/main/java/com/selfxdsd/storage/SelfInvoices.java, src/test/java/com/selfxdsd/storage/SelfInvoicesITCase.java, src/test/resources/insertTestData.sql
=> #101 SelfInvoices.registerAsPaid implemented and tested

pom.xml
=> #107 updated to core 0.0.18

src/main/java/com/selfxdsd/storage/SelfInvoices.java, src/test/java/com/selfxdsd/storage/SelfInvoicesITCase.java
Fixes #106 
Implemented SelfInvoices.createNewInvoice. It will first check for the existence of the Contract.
Wrote tests for it.
=> #106 SelfInvoices.createNewInvoice + tests

pom.xml, src/main/java/com/selfxdsd/storage/SelfTasks.java, src/test/java/com/selfxdsd/storage/SelfTasksITCase.java
fixes #110 
Updated core to version 0.0.19
Implemented and tested SelfTasks.assign(...)
Left puzzle to unignore test.
=> #110 SelfTasks.assign(...) implemented

pom.xml, src/main/java/com/selfxdsd/storage/SelfContributors.java, src/main/java/com/selfxdsd/storage/SelfTasks.java
Fixes #113 
Left puzzles to continue work.
=> #113 self-core 0.0.20 and puzzles

src/main/java/com/selfxdsd/storage/SelfTasks.java, src/test/java/com/selfxdsd/storage/SelfTasksITCase.java
PR for #112 
Using Task.issueId() when assigning a Task.
Fixed test.
=> #112 Using task.issueId() and fix test

src/main/java/com/selfxdsd/storage/SelfContributors.java, src/test/java/com/selfxdsd/storage/SelfContractsITCase.java, src/test/java/com/selfxdsd/storage/SelfContributorsITCase.java, src/test/java/com/selfxdsd/storage/SelfJooqTestCase.java
=> #116. Implemented and tested paging for SelfContributors.

src/main/java/com/selfxdsd/storage/SelfProjects.java, src/test/java/com/selfxdsd/storage/SelfProjectsITCase.java
=> #119. SelfProjects using current page on queries.

src/test/resources/createDb.sql
=> #121. Fixed `slf_tasks_xdsd` fk reference of `slf_contracts_xdsd`.

src/main/java/com/selfxdsd/storage/SelfTasks.java, src/test/java/com/selfxdsd/storage/SelfTasksITCase.java, src/test/resources/insertTestData.sql
PR for #115 
A task can now be unassigned.
=> #115 SelfTasks.unassing(Task) implemented and tested

src/main/java/com/selfxdsd/storage/SelfTasks.java, src/test/java/com/selfxdsd/storage/SelfTasksITCase.java, src/test/resources/insertTestData.sql
=> #125 SelfTasks.remove(Task) implemented and tested

pom.xml, src/main/java/com/selfxdsd/storage/SelfJooq.java
Fixes #127 
Left puzzles to implement Resignations and Wallets
=> #127 core 0.0.21 and puzzles

src/main/java/com/selfxdsd/storage/SelfResignations.java, src/test/java/com/selfxdsd/storage/SelfContractsITCase.java, src/test/java/com/selfxdsd/storage/SelfResignationsITCase.java, src/test/resources/insertTestData.sql
PR for #133 
Methods register(...) and ofProject(...) implemented and tested.
=> #133 SelfResignations implemented

src/main/java/com/selfxdsd/storage/SelfContracts.java, src/test/java/com/selfxdsd/storage/SelfContractsITCase.java
=> #142. Register not found contributor on new contract.

pom.xml, src/main/java/com/selfxdsd/storage/SelfJooq.java
Fixes #144
Left puzzle to continue work on ``SelfPayoutMethods``.
=> #144 slef-core 0.0.22 + puzzle

src/main/java/com/selfxdsd/storage/SelfUsers.java
=> #148 make sure email and role of User never come null from the DB

pom.xml, src/main/java/com/selfxdsd/storage/SelfContributors.java, src/main/java/com/selfxdsd/storage/SelfPms.java, src/test/java/com/selfxdsd/storage/SelfPmsITCase.java
Fixes #151 
Left puzzle to implement SelfContributors.ofProvider(...)
=> #151 core 25; implemented and tested PMs.getByUsername

src/main/java/com/selfxdsd/storage/SelfContributors.java, src/test/java/com/selfxdsd/storage/SelfContributorsITCase.java, src/test/resources/insertTestData.sql
=> #154 Implemented+tested SelfContributors#ofProvider.

pom.xml, src/main/java/com/selfxdsd/storage/SelfWallets.java, src/test/java/com/selfxdsd/storage/SelfWalletsITCase.java
Fixes #156 
Updated self-core to 0.0.27
Made SelfWallets handle STRIPE wallets as well.
=> #156 register and read STRIPE wallets

pom.xml, src/main/java/com/selfxdsd/storage/SelfJooq.java, src/main/java/com/selfxdsd/storage/SelfWallets.java
Fixes #160 
Updated self-core and left puzzles to continue work.
=> #160 Updated to self-core 0.0.29

src/main/java/com/selfxdsd/storage/SelfPaymentMethods.java, src/test/java/com/selfxdsd/storage/SelfPaymentMethodsITCase.java, src/test/java/com/selfxdsd/storage/SelfProjectsITCase.java, src/test/resources/insertTestData.sql
PR for #165 
Implemented and tested methods register(...), remove(...) and activate(...)
=> #165 Completed implementation of SelfPaymentMetiod

src/main/java/com/selfxdsd/storage/SelfWallets.java, src/test/java/com/selfxdsd/storage/SelfWalletsITCase.java, src/test/resources/insertTestData.sql
=> #162 Implemented+tested SelfWallets#updateCash.

pom.xml, src/main/java/com/selfxdsd/storage/SelfContracts.java, src/main/java/com/selfxdsd/storage/SelfContributors.java, src/main/java/com/selfxdsd/storage/SelfTasks.java
=> #169 updated self-core to 0.0.30; left puzzles

src/main/java/com/selfxdsd/storage/SelfContracts.java, src/test/java/com/selfxdsd/storage/SelfContractsITCase.java
=> #172 SelfContracts.update(...) implemented and tested

pom.xml, src/main/java/com/selfxdsd/storage/SelfContracts.java, src/main/java/com/selfxdsd/storage/SelfPaymentMethods.java, src/main/java/com/selfxdsd/storage/SelfWallets.java, src/test/java/com/selfxdsd/storage/SelfContractsITCase.java, src/test/resources/createDb.sql, src/test/resources/insertTestData.sql
Fixes #177 
Changes:
- Updated self-core dependency to 0.0.36;
- Implemented and tested SelfContracts.remove(Contract);
- Added Wallet.identifier and Wallet.paymentMethodSetupIntent() delegator methods where needed;
=> Updated self-core to 0.0.36

pom.xml, src/main/java/com/selfxdsd/storage/SelfTasks.java, src/main/java/com/selfxdsd/storage/SelfWallets.java, src/test/java/com/selfxdsd/storage/SelfTasksITCase.java, src/test/java/com/selfxdsd/storage/SelfWalletsITCase.java
=> #185 core 0.0.39, FakeWallet and Estimation adapted

pom.xml, src/main/java/com/selfxdsd/storage/SelfContracts.java, src/test/java/com/selfxdsd/storage/SelfContractsITCase.java, src/test/java/com/selfxdsd/storage/SelfInvoicesITCase.java
Fixes #188 
Updated to self-core 0.0.41
Allow Contract restore (set markForRemoval to null).
=> #188 core 0.0.41 and allow Contract restore

pom.xml, src/main/java/com/selfxdsd/storage/SelfContracts.java, src/main/java/com/selfxdsd/storage/SelfProjects.java, src/test/java/com/selfxdsd/storage/SelfContractsITCase.java
Fixes #191
Updated to self-core 0.0.42;
Implemented and tested SelfContracts.count();
Left puzzle to implement and test SelfProjects.remove(...);
=> #191 updated to self-core 0.0.42

src/main/java/com/selfxdsd/storage/SelfProjects.java, src/test/java/com/selfxdsd/storage/SelfProjectsITCase.java, src/test/resources/createDb.sql, src/test/resources/insertTestData.sql
PR for #193 
Added test data;
Implemented and tested SelfProjects.remove(Project);
=> #193 Implemented and tested SelfProjects.remove(Project)

pom.xml, src/main/java/com/selfxdsd/storage/SelfInvoices.java, src/main/java/com/selfxdsd/storage/SelfPayoutMethods.java, src/main/java/com/selfxdsd/storage/SelfWallets.java, src/test/java/com/selfxdsd/storage/SelfInvoicesITCase.java
=> #199 updated to self-core 0.0.44

pom.xml, src/main/java/com/selfxdsd/storage/SelfProjects.java, src/test/java/com/selfxdsd/storage/SelfInvoicesITCase.java
PR for #222 
Updated to self-core 0.0.55
Adapted SelfProjects to pass the Storage to UserProjects and PmProjects.
=> #222 core 55; pass Storage to UserProjects and PmProjects

src/main/java/com/selfxdsd/storage/SelfApiTokens.java, src/test/java/com/selfxdsd/storage/SelfApiTokensITCase.java, src/test/resources/insertTestData.sql
PR for #235 
Implemented and tested the ofUser(...) method;
=> #235 SelfApiTokens.ofUser(...) implemented and tested

src/main/java/com/selfxdsd/storage/SelfApiTokens.java
=> #237 User email empty string if null

src/main/java/com/selfxdsd/storage/SelfApiTokens.java, src/test/java/com/selfxdsd/storage/SelfApiTokensITCase.java
=> #242 SelfApiTokens.register(...) implemented and tested

src/main/java/com/selfxdsd/storage/SelfApiTokens.java, src/test/java/com/selfxdsd/storage/SelfApiTokensITCase.java, src/test/resources/insertTestData.sql
=> #243 SelfApiTokens.remove(...) implemented and tested

src/main/java/com/selfxdsd/storage/SelfPayoutMethods.java, src/test/java/com/selfxdsd/storage/SelfPayoutMethodsITCase.java
=> #249 SelfPayoutMethods.remove(PayoutMethod) implemented and tested

src/main/java/com/selfxdsd/storage/SelfInvoices.java, src/test/java/com/selfxdsd/storage/SelfInvoicesITCase.java
=> #254 SelfInvoices.registerAsPaid(...) sets country and eurToRon

pom.xml, src/main/java/com/selfxdsd/storage/SelfPaymentMethods.java, src/main/java/com/selfxdsd/storage/SelfWallets.java
Fixes #256 
Left puzzles to implement 2 new methods.
=> #256 core 66 and puzzles

src/main/java/com/selfxdsd/storage/SelfPaymentMethods.java, src/test/java/com/selfxdsd/storage/SelfPaymentMethodsITCase.java
=> #261 SelfPaymentMethods.deactivate(...) implemented and tested

src/main/java/com/selfxdsd/storage/SelfWallets.java, src/test/java/com/selfxdsd/storage/SelfWalletsITCase.java, src/test/resources/insertTestData.sql
=> #260 SelfWallets.remove(Wallet) implemented and tested

pom.xml, src/main/java/com/selfxdsd/storage/SelfInvoices.java, src/test/java/com/selfxdsd/storage/SelfInvoicesITCase.java, src/test/java/com/selfxdsd/storage/SelfPlatformInvoicesITCase.java
=> #269 updated to core 68

src/main/java/com/selfxdsd/storage/SelfInvoices.java
=> #267 SelfInvoices.registerAsPaid(...) inserts successful Payment

pom.xml, src/main/java/com/selfxdsd/storage/SelfInvoices.java, src/main/java/com/selfxdsd/storage/SelfPayments.java
Fixes #273 
Updated to core 69 and passed invoiceId to StoredPayment.
=> #273 updated to core 69

src/main/java/com/selfxdsd/storage/SelfWallets.java, src/test/java/com/selfxdsd/storage/SelfWalletsITCase.java
=> #272 use Wallet decorators

src/test/java/com/selfxdsd/storage/SelfInvoicesITCase.java
=> #275 unignored test

pom.xml, src/main/java/com/selfxdsd/storage/SelfContracts.java, src/main/java/com/selfxdsd/storage/SelfInvoicedTasks.java, src/main/java/com/selfxdsd/storage/SelfInvoices.java, src/main/java/com/selfxdsd/storage/SelfPms.java, src/main/java/com/selfxdsd/storage/SelfProjects.java, src/main/java/com/selfxdsd/storage/SelfTasks.java, src/test/java/com/selfxdsd/storage/SelfInvoicedTasksITCase.java, src/test/java/com/selfxdsd/storage/SelfInvoicesITCase.java, src/test/java/com/selfxdsd/storage/SelfPlatformInvoicesITCase.java, src/test/java/com/selfxdsd/storage/SelfPmsITCase.java
Closes #280 
Updated to self-core 72 and left a bunch of puzzles to continue implementing the required changes.
=> #280 updated to core 72 + puzzles

src/main/java/com/selfxdsd/storage/SelfInvoicedTasks.java
PR for #287 
Avoid performing the Select at each Supplier.get();
=> #287 pass the list to the supplier

pom.xml, src/main/java/com/selfxdsd/storage/SelfJsonStorage.java, src/test/java/com/selfxdsd/storage/SelfJsonStorageITCase.java
=> #298 core 88; SelfJsonStorage reimplemented

src/main/java/com/selfxdsd/storage/SelfProjects.java, src/test/java/com/selfxdsd/storage/SelfContractsITCase.java, src/test/java/com/selfxdsd/storage/SelfProjectsITCase.java, src/test/resources/insertTestData.sql
PR for #305 
Implemented and tested renaming of a Project.
=> #305 SelfProjects.rename(...) implemented and tested

pom.xml, src/main/java/com/selfxdsd/storage/SelfProjects.java, src/test/java/com/selfxdsd/storage/SelfProjectsITCase.java
=> #308 removed Projects.getByWebHookToken

src/main/java/com/selfxdsd/storage/SelfTasks.java, src/test/java/com/selfxdsd/storage/SelfTasksITCase.java
=> #315 implemented updateEstimation(...) + tests

docker-compose.yml
Fixes #323 
* MySQL DB Container
* Create DB Init Script
* Volume for data persistence between containers
=> #323 docker compose for mysql
